NutriPaulo/Models/RelatorioPrincipal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NutriPaulo.Models
{
    public class RelatorioPrincipal
    {
        [Key]
        public int RelatorioPrincipalId { get; set; }
        public int PessoasId { get; set; }
        public virtual Pessoas Pessoas { get; set; }
    }
}

NutriPaulo/Controllers/PessoasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NutriPaulo.Contexto;
using NutriPaulo.Models;

namespace NutriPaulo.Controllers
{
    public class PessoasController : Controller
    {
        private readonly NutriContexto _context;

        public PessoasController(NutriContexto context)
        {
            _context = context;
        }

        // GET: Pessoas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pessoas.ToListAsync());
        }

        // GET: Pessoas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoas = await _context.Pessoas
                .FirstOrDefaultAsync(m => m.PessoasId == id);
            if (pessoas == null)
            {
                return NotFound();
            }

            return View(pessoas);
        }

        // GET: Pessoas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pessoas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PessoasId,Nome,SobreNome,CPF,RG,Email")] Pessoas pessoas)
        {
            if (ModelState.IsValid)
            {
                
                _context.Add(pessoas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pessoas);
        }


        // GET: Pessoas/Create
        public IActionResult Biotipo()
        {
            return View();
        }

        // POST: Pessoas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Biotipo([Bind("PessoasId,Nome,SobreNome,CPF,RG,Email")] Pessoas pessoas)
        {
            if (ModelState.IsValid)
            {

                _context.Add(pessoas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pessoas);
        }

        // GET: Pessoas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoas = await _context.Pessoas.FindAsync(id);
            if (pessoas == null)
            {
                return NotFound();
            }
            return View(pessoas);
        }

        // POST: Pessoas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PessoasId,Nome,SobreNome,CPF,RG,Email")] Pessoas pessoas)
        {
            if (id != pessoas.PessoasId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pessoas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PessoasExists(pessoas.PessoasId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pessoas);
        }

        // GET: Pessoas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoas = await _context.Pessoas
                .FirstOrDefaultAsync(m => m.PessoasId == id);
            if (pessoas == null)
            {
                return NotFound();
            }

            return View(pessoas);
        }

        // POST: Pessoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pessoas = await _context.Pessoas.FindAsync(id);
            _context.Pessoas.Remove(pessoas);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PessoasExists(int id)
        {
            return _context.Pessoas.Any(e => e.PessoasId == id);
        }
    }
}

NutriPaulo/Controllers/RelatorioPrincipalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NutriPaulo.Contexto;
using NutriPaulo.Models;

namespace NutriPaulo.Controllers
{
    public class RelatorioPrincipalsController : Controller
    {
        private readonly NutriContexto _context;

        public RelatorioPrincipalsController(NutriContexto context)
        {
            _context = context;
        }

        // GET: RelatorioPrincipals
        public async Task<IActionResult> Index()
        {
            var nutriContexto = _context.RelatorioPrincipal.Include(r => r.Pessoas);
            return View(await nutriContexto.ToListAsync());
        }


        public async Task<IActionResult> Home()
        {
            
            return View();
        }

        // GET: RelatorioPrincipals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var relatorioPrincipal = await _context.RelatorioPrincipal
                .Include(r => r.Pessoas)
                .FirstOrDefaultAsync(m => m.RelatorioPrincipalId == id);
            if (relatorioPrincipal == null)
            {
                return NotFound();
            }

            return View(relatorioPrincipal);
        }

        // GET: RelatorioPrincipals/Create
        public IActionResult Create()
        {
            ViewData["PessoasId"] = new SelectList(_context.Pessoas, "PessoasId", "PessoasId");
            return View();
        }

        // POST: RelatorioPrincipals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RelatorioPrincipalId,PessoasId")] RelatorioPrincipal relatorioPrincipal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(relatorioPrincipal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PessoasId"] = new SelectList(_context.Pessoas, "PessoasId", "PessoasId", relatorioPrincipal.PessoasId);
            return View(relatorioPrincipal);
        }

        // GET: RelatorioPrincipals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var relatorioPrincipal = await _context.RelatorioPrincipal.FindAsync(id);
            if (relatorioPrincipal == null)
            {
                return NotFound();
            }
            ViewData["PessoasId"] = new SelectList(_context.Pessoas, "PessoasId", "PessoasId", relatorioPrincipal.PessoasId);
            return View(relatorioPrincipal);
        }

        // POST: RelatorioPrincipals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RelatorioPrincipalId,PessoasId")] RelatorioPrincipal relatorioPrincipal)
        {
            if (id != relatorioPrincipal.RelatorioPrincipalId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(relatorioPrincipal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RelatorioPrincipalExists(relatorioPrincipal.RelatorioPrincipalId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PessoasId"] = new SelectList(_context.Pessoas, "PessoasId", "PessoasId", relatorioPrincipal.PessoasId);
            return View(relatorioPrincipal);
        }

        // GET: RelatorioPrincipals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var relatorioPrincipal = await _context.RelatorioPrincipal
                .Include(r => r.Pessoas)
                .FirstOrDefaultAsync(m => m.RelatorioPrincipalId == id);
            if (relatorioPrincipal == null)
            {
                return NotFound();
            }

            return View(relatorioPrincipal);
        }

        // POST: RelatorioPrincipals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var relatorioPrincipal = await _context.RelatorioPrincipal.FindAsync(id);
            _context.RelatorioPrincipal.Remove(relatorioPrincipal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RelatorioPrincipalExists(int id)
        {
            return _context.RelatorioPrincipal.Any(e => e.RelatorioPrincipalId == id);
        }
    }
}

NutriPaulo/Views/RelatorioPrincipals/Create.cshtml
@model NutriPaulo.Models.RelatorioPrincipal




<h4>RelatorioPrincipal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PessoasId" class="control-label"></label>
                <select asp-for="PessoasId" class="form-control" asp-items="ViewBag.PessoasId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<style>

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        background-color: #3f51b5;
    }


    .Titulo {
        margin:0 auto;
        text-align:center;
    }   
</style>

NutriPaulo/Views/RelatorioPrincipals/Delete.cshtml
@model NutriPaulo.Models.RelatorioPrincipal

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RelatorioPrincipal</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pessoas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pessoas.PessoasId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RelatorioPrincipalId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

NutriPaulo/Views/RelatorioPrincipals/Details.cshtml
@model NutriPaulo.Models.RelatorioPrincipal

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>RelatorioPrincipal</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pessoas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pessoas.PessoasId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RelatorioPrincipalId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

NutriPaulo/Views/RelatorioPrincipals/Edit.cshtml
@model NutriPaulo.Models.RelatorioPrincipal

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>RelatorioPrincipal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RelatorioPrincipalId" />
            <div class="form-group">
                <label asp-for="PessoasId" class="control-label"></label>
                <select asp-for="PessoasId" class="form-control" asp-items="ViewBag.PessoasId"></select>
                <span asp-validation-for="PessoasId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NutriPaulo/Views/RelatorioPrincipals/Home.cshtml
<main>



    <div class="conteudo">

        <div>
            <h1>Nutricionista</h1>
            <h2>Paulo Santos</h2>
            <h4>
                Especializada em Atendimento Clínico e Terapêutico Nutricional. Foi fundada em Janeiro 2010, com objetivo de oferecer atendimento individualizado ás pessoas que necessitam conhecer e usufruir dos valores nutricionais dos alimentos que são ingeridos diariamente.
            </h4>







        </div>
        <div class="conteudoInferior">
            <button class="meubtn"> <a href='@Url.Action("Create", "Pessoas")' class="btn btn-primary"> Faça uma avaliação ! </a> </button>
        </div>
     
   
    </div>

</main>





<style>
    

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    .conteudo {
        display: flex;
        background-color: #3f51b5;
        height: 100vh;
        align-items: center;
        justify-content: center;
        font-family: sans-serif;
        color: #f9fbe7;
        flex-direction:column;
    }

        .conteudo h1 {
            font-size: 120px;
            text-align: center;
        }

        .conteudo h2 {
            margin: 0 auto;
            text-align: center;
        }

        .conteudo h4 {
            margin-top: 30px;
            width: 700px;
            text-align: center;
            margin-left: 30px;
            font-weight: lighter;
        }

        a{
            text-decoration:none;
        }

    .meubtn {
        padding: 20px 20px;
        border-radius: 10px;
        border: none;
        font-family: sans-serif;
       margin: 0 auto;
    }

    .conteudoInferior{
        margin-top:30px;
        font-family:sans-serif;
        font-weight:bold;
    }
</style>

NutriPaulo/Views/RelatorioPrincipals/Index.cshtml
@model IEnumerable<NutriPaulo.Models.RelatorioPrincipal>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>


    <h1 style="text-align:center">Relatório De Pacientes</h1>


    <table class="table table-hover table-dark mt-4 text-center " style="margin:0 auto">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("Paciente")
                </th>
                <th>
                    @Html.DisplayName("CPF")
                </th>
                <th>
                    @Html.DisplayName("RG")
                </th>
                <th>
                    @Html.DisplayName("Email")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pessoas.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pessoas.CPF)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pessoas.RG)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pessoas.Email)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.RelatorioPrincipalId">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.RelatorioPrincipalId">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.RelatorioPrincipalId">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>


<style>


    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    table {
        width: 400px;
    }

    body {
        font-family: sans-serif;
        background-color: #3f51b5;
        color: #f9fbe7;
    }
</style>